### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'DJANGO'

### ISSUE THREAD

**Issue by raeuz** [ozgebarbaros/helpdesk#12]
Dear All,

I setup the helpdesk, run "python manage.py syncdb", the got bellow errors, how to fix this problem? Thansk.

```
F:\workspace\myprograms\helpdesk>f:\virtualenvs\helpdesk_py27_django17\Scripts\activate.bat
(helpdesk_py27_django17) F:\workspace\myprograms\helpdesk>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "F:\virtualenvs\helpdesk_py27_django17\lib\site-packages\django-1.7.7-py2.7.egg\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "F:\virtualenvs\helpdesk_py27_django17\lib\site-packages\django-1.7.7-py2.7.egg\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "F:\virtualenvs\helpdesk_py27_django17\lib\site-packages\django-1.7.7-py2.7.egg\django\conf\__init__.py", line 46, in __getattr__
    self._setup(name)
  File "F:\virtualenvs\helpdesk_py27_django17\lib\site-packages\django-1.7.7-py2.7.egg\django\conf\__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "F:\virtualenvs\helpdesk_py27_django17\lib\site-packages\django-1.7.7-py2.7.egg\django\conf\__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "F:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "F:\workspace\myprograms\helpdesk\helpdesk\settings.py", line 22, in <module>
    DJANGOSETTINGS=DjangoSettings()
  File "F:\workspace\myprograms\helpdesk\helpdesk\readconf.py", line 80, in __init__
    self.secret_key=config.get(section,"secret_key")
  File "F:\Python27\Lib\ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'DJANGO'

(helpdesk_py27_django17) F:\workspace\myprograms\helpdesk>
```

**Comment by ozgebarbaros** [comment]
Hi,
If you look over helpdesk/settings.py file, you will see COMMON_CONFIG_FILE variable. You should change this variable's value with path of your config file which contains [DB] and [DJANGO] sections. Content of your config file should be like this:
[DB]
host: 
port: 
database: (database name)
dbuser:
pass: 

[DJANGO]
secret_key: (secret_key is randomly genereted string for security of your application)

**Comment by raeuz** [comment]
Thank you.
I have set up sucessed.
But The feature is very sample. I am looking helpdesk with  adding watcher.
The helpdesk(https://github.com/rossp/django-helpdesk) also does not have this feature. 
Any suggestion?

**Comment by raeuz** [comment]
I found some issue tracker written in PHP or Java meets my needs.
But i want to learn Python/Django, so i look for issue tracker written in Python, but  not complex.
I think Trac(written in Python) is too much complex.

**Comment by ozgebarbaros** [comment]
We wrote this application for exercising Python and Django. Normally,it does not meet your requirements.  In this application, there is users, departments, department related services, department admins which can be added from Django admin interface (ex: localhost:8000/admin). Also, from Django admin interface you can assign roles to users. You are free to add "watcher" feature to our project;)

**Comment by raeuz** [comment]
I am just learning program now, so i look one system that meets my needs, and then i review code to learn:)
